name: Challenge-chapter-2
on: push
jobs:
    job1:
        name: Ubuntu job
        runs-on: ubuntu-latest
        steps:
            - name: Print Date
              run: echo "$(date)"
    job2:
        name: Windows job
        runs-on: windows-latest
        steps:
            - name: Print Date
              run: echo "$(date)"
    job3:
        name: MacOS job
        runs-on: macos-latest
        steps:
            - name: Print Date
              run: echo "$(date)"
    job4:
        name: Fourth job
        runs-on: macos-latest
        needs: [job1,job2,job3]
        steps:
            - name: Print Date
              run: echo "$(date)"


           
