name: myOwnCI
on: 
      pull_request:
    # push:
        branches:
          - 'main'
          - 'release/*'
        # branches-ignore:
        #   - 'release/old-*'
        # tags:
        #     - 'v1.*'
        # tags-ignore:
        #     - 'v2.*'

jobs:
    job1:
        name: Ubuntu job
        runs-on: ubuntu-latest
        steps:
        - name: Step one
          uses: actions/checkout@v2
        - name: Step two
          run: env | sort
    job2:
        name: Windows job
        runs-on: windows-latest
        needs: [job1]
        steps:
        - name: Step one
          uses: actions/checkout@v2
        - name: Step two
          run: "Get-ChildItem Env: | Sort-Object Name"
    job3:
        name: Macos job
        runs-on: macos-latest
        needs: [job1,job2]
        steps:
        - name: Step one
          uses: actions/checkout@v2
        - name: Step two
          run: echo "Hello from macos runner"